<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>    
    <LangVersion>preview</LangVersion>
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src/zig_parser.fs" />
    <Compile Include="src/doc_generator.fs" />
    <Compile Include="src/fs_generator.fs" />
    <Compile Include="src/cs_generator.fs" />
    <Compile Include="src/ProgramV2.fs" />
  </ItemGroup>


</Project>
